#pragma once

#include "CoreMinimal.h"
#include "UIEventDeclarationMacros.h"

// Generated by RefreshUIEventContracts. Do not edit by hand.

namespace UIEvents
{
namespace Player
{
inline const FName HPChanged = TEXT("Player.HPChanged");
}
}

namespace UIEvents
{
namespace Player
{
namespace HUD
{
inline const FName ConnectRequested = TEXT("Player.HUD.ConnectRequested");
}
}
}

namespace UIEvents
{
namespace Player
{
namespace HUD
{
inline const FName Constructed = TEXT("Player.HUD.Constructed");
}
}
}

namespace UIEvents
{
namespace Player
{
namespace HUD
{
inline const FName DamageButtonClicked = TEXT("Player.HUD.DamageButtonClicked");
}
}
}

namespace UIEvents
{
namespace Player
{
namespace HUD
{
inline const FName HealButtonClicked = TEXT("Player.HUD.HealButtonClicked");
}
}
}

