#pragma once

#include "CoreMinimal.h"
#include "UIEventDeclarationMacros.h"

// Generated by RefreshUIEventContracts. Do not edit by hand.

namespace UIEvents
{
namespace Model
{
namespace Player
{
inline const FName HPChanged = TEXT("Model.Player.HPChanged");
}
}
}

namespace UIEvents
{
namespace View
{
namespace HUD
{
inline const FName Constructed = TEXT("View.HUD.Constructed");
}
}
}

namespace UIEvents
{
namespace View
{
namespace HUD
{
inline const FName DamageButtonClicked = TEXT("View.HUD.DamageButtonClicked");
}
}
}

namespace UIEvents
{
namespace View
{
namespace HUD
{
inline const FName HealButtonClicked = TEXT("View.HUD.HealButtonClicked");
}
}
}

